### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by gabriel-pcr** [pandatix/js-cvss#9]
I am using Vue 3 and ran the command

`npm install '@pandatix/js-cvss' -D`

However, when I import or try to use the lib the following error is shown:

```
[vite] Internal server error: Failed to resolve entry for package "@pandatix/js-cvss". The package may have incorrect main/module/exports specified in its package.json.
Plugin: vite:import-analysis
```

I'm importing it like below:
`import {CVSS40} from "@pandatix/js-cvss";`

**Comment by pandatix** [comment]
I will look into this issue a bit later today.

In the meantime, maybe @chandanbn have an idea of what could be the underlying problem as I know he used it successfully for Vulnogram :)

**Comment by gabriel-pcr** [comment]
Great. Please let me know if an update comes up.

**Comment by pandatix** [comment]
@gabriel-pcr is `v0.4.4` better ?

**Comment by gabriel-pcr** [comment]
It's fixed. Thank you.
